// <auto-generated />
namespace ArkTradingEvolvedWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedadminusertoseedmethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedadminusertoseedmethod));
        
        string IMigrationMetadata.Id
        {
            get { return "201804042345243_Added admin user to seed method"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
